DELETE FROM `position`;

INSERT INTO `position` (`position_id`, `position_name`, `position_desc`, `position_dept`, `position_res`, `position_status`) 
VALUES 
(1, 'Product Designer', 'We are seeking a Product Designer with a passion for finding solutions that allow customers to intuitively use our products.', 'IT Team', 'Set design requirements based on information from internal teams and user research;Identify new product improvement opportunities;Analyze how a new product satisfies market needs and consumer preferences;Coordinate with other design team members to ensure consistent and accurate communication;Modify and revise existing designs to meet changing customer preferences.', 'Active'),
(2, 'Software Engineer', 'We are looking for a passionate Software Engineer to design, develop and install software solutions.', 'IT Team', 'Executing full lifecycle software development;Programming well-designed, testable, efficient code;Producing specifications and determine operational feasibility', 'Active'),
(3, 'Staff Software Engineer', 'We are looking for a detail-oriented staff engineer to collaborate on the improvement of our systems. You will be overseeing the structural design process, estimating costs, and performing quality control throughout the stages of implementation.', 'IT Team', 'Evaluating existing processes and procedures to identify areas that need optimization;Projecting the costs and timeframes of projects, as well as creating work schedules and setting deadlines', 'Active'), 
(4, 'Human Resources', 'We are looking for a skilled HR Officer who will recruit, support and develop talent through developing policies and managing procedures.', 'Human Resource', 'Supporting the development and implementation of HR initiatives and systems;Providing counseling on policies and procedures;Being actively involved in recruitment by preparing job descriptions, posting ads and managing the hiring process', 'Active'),
(5, 'Administrative Assistant', 'We are looking for an Administrative Officer to join our team and support our daily office procedures.', 'Operations', 'Managing office supplies stock and placing orders;Preparing regular financial and administrative reports;Administration of company databases', 'Retired'),
(6, 'Finance Manager', 'We are looking for a reliable Financial Manager that will analyze every day financial activities and subsequently provide advice and guidance to upper management on future financial plans.', 'Finance', 'Providing financial reports and interpreting financial information to managerial staff while recommending further courses of action;Advising on investment activities and provide strategies that the company should take;Maintaining the financial health of the organization', 'Active'),
(7, 'Finance Executive', 'We are looking for a Finance Executive to take charge of the financial health of our company by administering accounting operations to meet legal requirements.', 'Finance', 'Managing office supplies stock and placing orders;Preparing regular financial and administrative reports;Administration of company databases', 'Active'),
(8, 'Call Center Manager', 'We are looking for a skilled Call center manager to supervise daily operations and personnel aiming for maximum efficiency and cost-effectiveness.', 'Operations', 'Developing objectives for the call center’s day-to-day activities;Conducting effective resource planning to maximize the productivity of resources (people, technology etc.);Collecting and analyzing call-center statistics (sales rates, costs, customer service metrics etc.)', 'Active'),
(9, 'Sales Manager', 'We are looking for a high-performing Sales Manager to help us meet our customer acquisition and revenue growth targets by keeping our company competitive and innovative.', 'Sales', 'Achieving growth and hitting sales targets by successfully managing the sales team;Designing and implementing a strategic sales plan that expands company’s customer base and ensure it’s strong presence;Managing recruiting, objectives setting, coaching and performance monitoring of sales representatives', 'Active'),
(10, 'Sales Representative', 'We’re looking for a results-driven Sales Representative with excellent interpersonal skills to actively seek out and engage customer prospects.', 'Sales', 'Selling products and services using solid arguments to prospective customers;Performing cost-benefit analyses of existing and potential customers;Maintaining positive business relationships to ensure future sales', 'Active'),
(11, 'Technical Program Manager', 'We are looking for a Technical Program Manager who  will be responsible for partnering with product, engineering, and design teams to develop, manage, and accelerate efficient software development practices.', 'IT Team', 'Program coordination across engineering, business, and other departments;Developing and tracking progress against a roadmap;Scope prioritization, building schedules, and translating the business requirements into engineering consumable specs', 'Active'),
(12, 'Product Manager', 'We are looking for an experienced Product Manager who is passionate about building products that customers love.', 'IT Team', 'Creating buy-in for the product vision both internally and with key external partners;Developing product pricing and positioning strategies;Translating product strategy into detailed requirements and prototypes', 'Active'),
(13, 'QA Tester', 'We are looking for a QA Tester to assess software quality through manual and automated testing. You will be responsible for finding and reporting bugs and glitches.', 'IT Team', 'Reviewing and analyzing system specifications;Executing test scripts and reviewing results;Reporting and documenting technical issues', 'Active'),
(14, 'Operations Manager', 'We are looking for a professional Operations Manager to coordinate and oversee our organization’s operations.', 'Operations', 'Ensuring all operations are carried on in an appropriate, cost-effective way;Improving operational management systems, processes and best practices;Helping the organization’s processes remain legally compliant', 'Active'),
(15, 'Repair Engineer', 'We are looking for a Repair Engineer to provide advice as required on safety management systems, safety requirements and processes pertinent to railway testing and commissioning, operation and maintenance.', 'Operations', 'Designing/Documenting test methods across MR, CT, and XRRF systems for in house repair qualification at the Repair Operations Center;Equipment registrations;Diagnostics, quotations and parts orders if necessary', 'Retired'),
(16, 'Accountant', 'We are looking for an Accountant to manage all financial transactions, from fixed payments and variable expenses to bank deposits and budgets.', 'Finance', 'Tracking payments to internal and external stakeholders;Preparing budget forecasts;Processing tax payments and returns', 'Active'),
(17, 'Managing Director', 'We are looking for an experienced Managing Director to control and oversee all business operations, people and ventures.', 'Operations', 'Developing and executing the company’s business strategies;Providing strategic advice to the board and chairperson;Preparing and implementing comprehensive business plans to facilitate achievement', 'Retired'),
(18, 'Customer Service Representative', 'We are looking for a customer-oriented service representative.', 'Sales', 'Manage large amounts of incoming phone calls;Generate sales leads;Identify and assess customers’ needs to achieve satisfaction', 'Active'),
(19, 'Growth Manager', 'We are looking for a Growth Manager, who focuses on Client Acquisition and SEO.', 'Sales', 'Lead a team of 2-4 executives across Growth Marketing and SEO specialities (in-house / agency) to drive customer acquisition, activation and new monetization opportunities', 'Active'),
(20, 'IT Support', 'We are looking for an IT Support to ensure that our employees can use software and hardware to complete their daily tasks.', 'IT Team', 'Resolving IT support requests from employees;Answering employee questions regarding computer systems;Gathering and analyzing data to diagnose problems with computer systems', 'Active');
